/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "map_service_constants.h"

namespace map_service {

const map_serviceConstants g_map_service_constants;

map_serviceConstants::map_serviceConstants() {
}

} // namespace

