/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef map_service_CONSTANTS_H
#define map_service_CONSTANTS_H

#include "map_service_types.h"

namespace map_service {

class map_serviceConstants {
 public:
  map_serviceConstants();

};

extern const map_serviceConstants g_map_service_constants;

} // namespace

#endif
